#!/usr/bin/env bash
set -euo pipefail

# Resolve the directory where THIS script lives
SCRIPT_DIR="$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )"

# Project root = parent of scripts/
PROJECT_ROOT="$( dirname "$SCRIPT_DIR" )"

##
# Global configs and paths.
##
CURRENT_DIR=$(pwd)
CLAM_SRC_DIR="${CURRENT_DIR}/src/clam"
CLAM_BUILD_DIR="${CLAM_SRC_DIR}/build"
CLAM_INSTALL_DIR="${CLAM_BUILD_DIR}/install"
CRAB_SRC_DIR="${CURRENT_DIR}/src/crab"
ELINA_SRC_DIR="${CURRENT_DIR}/src/elina"

export BOOST_INSTALL_DIR=""
export GUROBI_HOME=""
export LIBTORCH_INSTALL_DIR=""
export Z3_HOME=""

##
# Helper functions.
##
log() { printf "\033[1;34m[build]\033[0m %s\n" "$*"; }
die() { printf "\033[1;31m[error]\033[0m %s\n" "$*" >&2; exit 1; }

usage()
{
    ##
    # Describes the usage of this script.
    ##
  cat <<EOF
Usage: $0 {scratch|incremental} [OPTIONS]

Modes:
  scratch      Clean build and rebuild everything from scratch.
  incremental  Incremental build for new changes.

Options:
  --boost PATH        Path to Boost install dir
  --gurobi PATH       Path to Gurobi install dir
  --libtorch PATH     Path to LibTorch install dir
  --z3 PATH           Path to Z3 install dir
  --write-env         Save provided paths into .env for next runs
  -h, --help          Show this help message
EOF
}

load_env()
{
    ##
    # Method to load the environment variables from the ".env" environment file.
    ##
    if [[ -f .env ]]; then
        set -a; source .env; set +a
        log "Loaded .env"
    else
        log "No .env found (that’s ok if you pass flags)."
    fi
}

parse_args()
{
    ##
    # Method to parse the arguments.
    ##
    MODE=""
    while [[ $# -gt 0 ]]; do
    case "$1" in
        scratch|incremental)
        if [[ -n "$MODE" ]]; then
            echo "Mode already set to '$MODE'. Only one mode allowed."
            usage; exit 1
        fi
        MODE="$1"
        shift
        ;;
        --boost) BOOST_INSTALL_DIR="${2?Missing path}"; shift 2 ;;
        --gurobi) GUROBI_HOME="${2?Missing path}"; shift 2 ;;
        --libtorch) LIBTORCH_INSTALL_DIR="${2?Missing path}"; shift 2 ;;
        --z3) Z3_HOME="${2?Missing path}"; shift 2 ;;
        --write-env) WRITE_ENV=1; shift ;;
        -h|--help) usage; exit 0 ;;
        *) echo "Unknown arg: $1"; usage; exit 1 ;;
    esac
    done

    if [[ -z "$MODE" ]]; then
    echo "Missing required mode: scratch or incremental"
    usage
    exit 1
    fi
}

resolve_path() {
  case "$1" in
    /*) echo "$1" ;;                   # already absolute
    *)  echo "$PROJECT_ROOT/$1" ;;     # prepend project root
  esac
}

validate_paths()
{
    ##
    # Method to validate the paths input/set by the user.
    ##

    # Resolve input
    BOOST_INSTALL_DIR="$(resolve_path "$BOOST_INSTALL_DIR")"
    GUROBI_HOME="$(resolve_path "$GUROBI_HOME")"
    LIBTORCH_INSTALL_DIR="$(resolve_path "$LIBTORCH_INSTALL_DIR")"
    Z3_HOME="$(resolve_path "$Z3_HOME")"

    # Quick sanity
    need_dir() { [[ -d "$1" ]] || die "Not a directory: $1"; }
    need_file() { [[ -f "$1" ]] || die "Missing file: $1"; }

    need_dir "$BOOST_INSTALL_DIR"
    need_dir "$GUROBI_HOME"
    need_dir "$LIBTORCH_INSTALL_DIR"
    need_dir "$Z3_HOME"

    log "All input paths look good."

    # Export names your CMake/builds expect
    export Boost_ROOT="$BOOST_INSTALL_DIR"
    export BOOST_PREFIX="$BOOST_INSTALL_DIR"
    export GUROBI_PREFIX="$GUROBI_HOME"
    export LIBTORCH_PREFIX="$LIBTORCH_INSTALL_DIR"
    export Z3_PREFIX="$Z3_HOME"

    # Compose helpful prefix path for find_package(Config)
    export CMAKE_PREFIX_PATH="${BOOST_INSTALL_DIR}:${Z3_HOME}:${LIBTORCH_INSTALL_DIR}:${CMAKE_PREFIX_PATH:-}"
}

maybe_write_env()
{
  ##
  # Write back to environment file if the option is on.
  ##
  [[ "${WRITE_ENV:-0}" -eq 1 ]] || return 0
  cat > .env <<EOF
# Generated by build.sh --write-env
BOOST_INSTALL_DIR=$BOOST_INSTALL_DIR
GUROBI_HOME=$GUROBI_HOME
LIBTORCH_INSTALL_DIR=$LIBTORCH_INSTALL_DIR
Z3_HOME=$Z3_HOME
EOF
  log "Wrote .env with resolved paths."
}

clean()
{
  log "Cleaning $CLAM_BUILD_DIR and temp artifacts"
  rm -rf "$CLAM_BUILD_DIR" "${CLAM_SRC_DIR}/llvm-seahorn" "${CLAM_SRC_DIR}/sea-dsa" "${CLAM_SRC_DIR}/tests/clam_config.py"
}

build_elina_from_scratch()
{
    ##
    # Commands to build elina from scratch.
    ##
    pushd ${ELINA_SRC_DIR} >/dev/null
    ./configure -prefix ${CLAM_INSTALL_DIR} -use-affine
    make clean
    make
    make install
    popd >/dev/null
}

rebuild_elina()
{
    ##
    # Commands to rebuild elina.
    ##
    pushd ${ELINA_SRC_DIR} >/dev/null
    make
    make install
    popd >/dev/null
}

configure_clam()
{
    ##
    # Configure CLAM for the build.
    ##
    log "Configuring main project (clam)"
    mkdir -p "$CLAM_BUILD_DIR"
    pushd "$CLAM_BUILD_DIR" >/dev/null
    cmake -G Ninja \
        -DCMAKE_INSTALL_PREFIX="${CLAM_INSTALL_DIR}" \
        -DCRAB_ROOT="${CRAB_SRC_DIR}" \
        -DCMAKE_BUILD_TYPE=Release \
        -DCMAKE_PREFIX_PATH="${CLAM_INSTALL_DIR};" \
        ../
    popd >/dev/null
}

build_clam()
{
    ##
    # Build CLAM.
    ##
    pushd "$CLAM_BUILD_DIR" >/dev/null
    cmake --build . --target extra
    cmake -DCRAB_USE_ELINA=ON -DELINA_ROOT="${CLAM_INSTALL_DIR}" ../
    cmake --build . --target install
    popd >/dev/null
}

rebuild_clam()
{
    ##
    # Rebuild CLAM.
    ##
    pushd "$CLAM_BUILD_DIR" >/dev/null
    cmake --build . --target install
    popd >/dev/null
}

main() {
  load_env
  parse_args "$@"
  validate_paths
  maybe_write_env

  case "${MODE}" in
    scratch)
      clean
      mkdir -p "$CLAM_BUILD_DIR" "$CLAM_INSTALL_DIR"
      build_elina_from_scratch
      configure_clam
      build_clam
      ;;
    incremental)
      [[ -d "$CLAM_BUILD_DIR" ]] || die "No existing build; run: $0 scratch"
      rebuild_elina
      rebuild_clam
      ;;
  esac

  log "Done."
}

main "$@"